default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: rails_group_project_development
test:
  <<: *default
  database: rails_group_project_test

# 
production:
  <<: *default
  database: rails_group_project_production
  username: rails_group_project
  password: <%= ENV["RAILS_GROUP_PROJECT_DATABASE_PASSWORD"] %>
